persons = [
    {
        "name": "Anna",
        "age": 25,
        "gender": "female"
    }, {
        "name": "Feris",
        "age": 31,
        "gender": "male"
    }, {
        "name": "Keanu",
        "age": 57,
        "gender": "male"
    }, {
        "name": "Angelina",
        "age": 46,
        "gender": "female"
    }, {
        "name": "Alex",
        "age": 42,
        "gender": "male"
    }, {
        "name": "Cortana",
        "age": 25,
        "gender": "female"
    }, {
        "name": "Carlsen",
        "age": 31,
        "gender": "male"
    }, {
        "name": "Jan",
        "age": 31,
        "gender": "male"
    }, {
        "name": "Florentino",
        "age": 74,
        "gender": "male"
    }, {
        "name": "Angelina",
        "age": 16,
        "gender": "female"
    }, {
        "name": "Alex",
        "age": 22,
        "gender": "male"
    }, {
        "name": "Alex",
        "age": 15,
        "gender": "male"
    }, {
        "name": "Alex",
        "age": 55,
        "gender": "female"
    }, {
        "name": "Jan",
        "age": 30,
        "gender": "male"
    }, {
        "name": "Dmitry",
        "age": 10,
        "gender": "male"
    }, {
        "name": "Max",
        "age": 4,
        "gender": "male"
    }, {
        "name": "Natasha",
        "age": 36,
        "gender": "female"
    }, {
        "name": "Vladimir",
        "age": 38,
        "gender": "male"
    }, {
        "name": "Aleksander",
        "age": 39,
        "gender": "male"
    }, {
        "name": "Fedor",
        "age": 38,
        "gender": "male"
    }, {
        "name": "Lyuba",
        "age": 37,
        "gender": "female"
    }
]